### ISSUE TITLE
Consider change ports 50001-50002 / Может быть нужно сменить порты 5000х

### ISSUE THREAD

**Issue by VK6NX** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#104]
В добавок к Энидеску теперь еще имеем Icom 9700, который тоже очень любит порты 50001-50002.

Может быть таки вернуться на 4000х, да еще и сделать что-то такое, типа 4115х, чтобы уж точно никто не попадал в этот рэнж?

-----------
Eng

Suggesting to move 5000x ports to different range (because of AnyDesk, IC-9700... surely something else there)

**Comment by rvolchkov** [comment]
Сделаем с новой прошивкой
