### ISSUE TITLE
"DX-pedition mode" для работы со спотами

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#109]
Запрос от команд работающих в DX-педициях, на внедрение "DX-pedition mode" для работы со спотами.
Клик по споту не должен перестраивать частоту передатчика, а только частоту приемника.

Повторение внутренней задачи [#3299]

**Comment by ExpertSDR3** [comment]
Сейчас левый клик по споту устанавливает частоту спота в VFOA, правый клик устанавливает частоту спота в VFOB.

**Comment by rvolchkov** [comment]
Думаю пойдет
