### ISSUE TITLE
MIDI Control support in eSDR3

### ISSUE THREAD

**Issue by John-KC2QMA** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#110]
It would be great to have MIDI control support built into eSDR3 to allow any MIDI device to control eSDR3. It could be added to the “Panel” menu like in eSDR2 for the E-Coder. The ANAN currently can support this.
Here is a video showing how it works:
https://youtu.be/XqqjrAyc3ag

**Comment by rvolchkov** [comment]
We do not plan to support third-party control panels
