### ISSUE TITLE
Any chance of EESDR ever using Audio Plug Ins Natively?

### ISSUE THREAD

**Issue by W1SPS** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#113]
I know you can get 3rd party software like Cakewalk or Avid Pro Tools to use plugins for the radio, but Is there any chance of EESDR ever having the capability of using audio plug ins directly?

**Comment by John-KC2QMA** [comment]
This topic has been suggested here:
https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS/issues/38#issue-1093621100

**Comment by 1972igor** [comment]
a very good question! You can make the PROC module switchable leaving only the Rotator and the VST plug-ins working

**Comment by rvolchkov** [comment]
Duplicates [Suggestion #38](https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS/issues/38#issue-1093621100)
