### ISSUE TITLE
New 4-band equalizer in EESDR3

### ISSUE THREAD

**Issue by dd5md** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#115]
To develop a new software and to advertise it as "The new generation of SDR software", where then a ready component like the "4-band equalizer" is implemented, which does not even come close to the current "8-band equalizer" in EESDR2, is completely incomprehensible to me.

It should be possible to display the current equalizer in EESDR3. The Equalizer or the PROC menu is for me one of the highlights in EESDR2.

It would be great if other users could be found who see this similarly.

**Comment by N8SDR007** [comment]
4 Band what are you looking at?

Does this look only 4 bands to you, if so, you must be using a limited edition etch a Stech
I see 8 Bands of fully parametric EQ, f
frequency adjusts
+/- Gain level adjust
Que adjusts

Plus, the added filter options for even more EQ abilities

I'm sorry don't take this wrong but you're not looking at the correct software! Period.  Heck even the RX EQ is 10 band 
 [Screenshot 2022-10-15 133048](https://user-images.githubusercontent.com/94698375/196000152-78f07536-ca10-4ce8-953f-38fefad1adf4.jpg)

**Comment by N8SDR007** [comment]
Still curious where you find or saw this 4 BAND EQ you speak of?

**Comment by rvolchkov** [comment]
Rick is correct, at the moment we have 8-band EQ in ESDR3.
