### ISSUE TITLE
RadioSync 1.20 Alpha

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#118]
Under the Audio settings it would very nice and helpful if there were some Gain sliders or options for controlling the audio gain on RX/TX

It would make this very useful for 3rd party application that are not TCI capable or ready

Currently the application works half assed- 

I have no way of controlling Virtual gain in or out of other applications.

**Comment by rvolchkov** [comment]
RX/TX gain are implemented in Sound card tab
