### ISSUE TITLE
initiate DHCP discovery

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#122]
initiate auto DHCP discovery and assignment of network interface

Would help A LOT with users who do not understand and don't want to bother with manual setup of IP addresses and switching there systems back and forth in order to get your product on their network,

This also helps for those that make changes to their network, perhaps not them directly but let's say their ISP provider has to replace onsite equipment and the new installed hardware or even better the Install Tech decides he is using a different IP range then what was previously being used. 

Now the User is screwed especially if they do not understand networking and do not know they need to reassign and new Ip address in the range of the new network installation otherwise the radio will not be seen by software any more.

DHCP needs to be implemented ASAP

**Comment by Antonello66** [comment]
It would cost more!! Sicosi is sometimes a bit cumbersome ....

**Comment by N8SDR007** [comment]
It wouldn't cost anymore
That's bullshit

It's already part of the network card internally. Just a matter of programing..




⁣Get BlueMail for Android ​

**Comment by Antonello66** [comment]
in development, in order of time....

**Comment by rvolchkov** [comment]
It'll be a part of the next gen firmware.
