### ISSUE TITLE
Where does full duplex stand never got a striaght answer

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#123]
In last  EE live stream i asked again where does Full Duplex stand but never got a staright answer.

If this still going to happen and if so any timeline updates?

**Comment by John-KC2QMA** [comment]
Yes please give us a detailed update on where EE is with Full-Duplex and Pre-Distortion with an explanation on how they will be implemented in hardware and software and about how long we can expect to see this in V3.
Thank You

**Comment by N8SDR007** [comment]
LOL-

**Comment by N8SDR007** [comment]
NEVER that is the general overall feeling now , NEVER,

**Comment by John-KC2QMA** [comment]
I guess these radios are not Full-Duplex or Adaptive Pre-Distortion capable as we have been told?
I hope we are incorrect but until anyone can explain clearly how this can be done with the current lineup of transceivers we will just have to assume that it’s not possible.

**Comment by N8SDR007** [comment]
All I can say

Is for past year plus.

Both Roman and Vasily have Said over and over said over and over we have duplex working on tests programmer is working on it. one of them is here- https://youtu.be/TMgmOMyaBy0?t=1412

There are several videos where they have openly said this over a year ago.

So, my gut tells me that really isn't the case and many were/ have been led on including myself.

. 



⁣Get BlueMail for Android ​

**Comment by rvolchkov** [comment]
It's not a suggestion, discussions are for the Forum.

**Comment by N8SDR007** [comment]
It was also on the forum no discussion there either 

⁣Get BlueMail for Android ​
