### ISSUE TITLE
Add stereo audio capability for broadcast FM stations.

### ISSUE THREAD

**Issue by williamscody** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#126]
Suggest adding stereo audio capability for broadcast FM stations.

**Comment by John-KC2QMA** [comment]
yes please

**Comment by John-KC2QMA** [comment]
V2 has FM Stereo so I'm sure V3 will have it at some point, it's just not a priority at the moment.

**Comment by rvolchkov** [comment]
Fix will be presented in the coming release
