### ISSUE TITLE
Space bar TX intermittent

### ISSUE THREAD

**Issue by M0mws** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#136]
Have noticed that the ability to toggle PTT with space bar is intermittent. 
This is normally used when I am running remote. Any one else had the same problem. Running latest version of EESDR3

**Comment by rvolchkov** [comment]
When we implement the proper key sequence, you'll be able to assign required functions to certain buttons. It'll be implemented after ESDR3 1.0.

**Comment by M0mws** [comment]
Good morning Roman,I hope you and your family had a good Xmas. Ok, thanks. Work round for me is to use my new Encoder2 button programmed for TX. It was my Xmas present to me. Thanks to you and your programmers. It worked fine out of the box. I will now sell the encoder plus. Looking forward to LAN operating when it gets cold from house not shack👌V3 very FB now. Have a good New Year. PSJust as well you warned about supplying 5v at 0.5A. My normal Panasonic Toughbook struggled with that. But powered hub cured it. Also I intend to use CAT6 not Wi-Fi😂WiFi only good for toys. 73Martin W Smith M0MWSOn 27 Dec 2022, at 07:31, Roman Volchkov ***@***.***> wrote:﻿
When we implement the proper key sequence, you'll be able to assign required functions to certain buttons. It'll be implemented after ESDR3 1.0.

**Comment by rvolchkov** [comment]
Hello Martin.
Thanks, I also wish you a happy Merry Christmas and only the best in the coming New Year!
That is a neat present you've prepared for yourself))) and great that you've remembered all this technicality with voltage and WLAN))

**Comment by M0mws** [comment]
Hi Roman,I have now bought. :-MB1SunSDR2 ProSunsdr2Pro DXEncoder PlusEncoder 2Does this mean I I have shares in EE now 😂😂Martin W Smith M0MWSOn 27 Dec 2022, at 08:55, Roman Volchkov ***@***.***> wrote:﻿
Hello Martin.
Thanks, I also wish you a happy Merry Christmas and only the best in the coming New Year!
That is a neat present you've prepared for yourself))) and great that you've remembered all this technicality with voltage and WLAN))
