### ISSUE TITLE
Spectrum RX/TX ExpertSDR3

### ISSUE THREAD

**Issue by ELSDR** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#14]
Who came up with the idea to freeze the spectrum RX and to stay in the spectrum when trx goes to TX ?
The fact that the red color tx spectrum appears is OK, but that both are present at time tx is not OK.

What is in V2 is great plus the addition that this spectrum in tx mode in V3 is red and no longer green great improvement :so_happy:
I don't think I'm the only user bothered by this in the V3 alpha version.
I hope that until the beta release this will be fixed or at least an option in what way the user wants to have rx/tx spectrum  and not both simultaneously in the spectrum.
This is not right and at the very start of development, the tx spectrum should already be without a frozen rx spectrum.
regards Elvis

**Comment by rvolchkov** [comment]
We won't be changing it for now, since it was requested by many users.
