### ISSUE TITLE
TCI command needed to set/read the internal CW keyer speed

### ISSUE THREAD

**Issue by dl2rum** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#2]
We need a TCI command to set/read the internal CW keyer speed similar to the CW_MACROS_SPEED command.

**Comment by ct1drb** [comment]
I agree with DL2RUM Tom to implement his request, it would be very useful indeed.

**Comment by ExpertSDR3** [comment]
The command has been added, in release 0.10 it will be.
cw_keyer_speed:wpm;
