### ISSUE TITLE
Launcher Window in 4K

### ISSUE THREAD

**Issue by F1DJY** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#26]
I am using 2X 4K displays. The size of the launcher window is huge and unsuitable. It would be good to make it configurable.

**Comment by danweecc** [comment]
I have a HD display in Linux and have the same problem. The feedback I got was that this was due to Qt but I think it needs to be fixed because other Qt applications don't do this.

**Comment by F1DJY** [comment]
I don't know what it came from, what is certain is that it is enough to make the window sizable to a smaller format. 73 Jean-marie

**Comment by rvolchkov** [comment]
It's fixed for normal operation in Linux
