### ISSUE TITLE
EESDR3 0.11.0 17122021 UI/UX suggestions

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#28]
Thanks for working on the new version and implementing some of the suggestions. Here are a few other suggestions:-

1. When you click on a button to pop-up a panel, re-clicking the same button should toggle it off. For example, clicking on the "i" on the top right for the information panel or the "i" on the bottom left for the firmware information, or the "Show Audio Mixer" button - when you click it the first time, the panel pops up. When you click it again, the panels should close.
2. The display of the VFO frequency in the Spectrum needs to be separated more in split mode. The way it is done currently makes it impossible to read as shown below.
![image](https://user-images.githubusercontent.com/13930571/146558955-f3257d7b-8ff4-4166-967d-e6215df80eca.png)

**Comment by rvolchkov** [comment]
Implemented
