### ISSUE TITLE
Fast A2/A3 antenna switch in main window (ESDR3 0.11.1 and up)

### ISSUE THREAD

**Issue by VK6NX** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#29]
Currently A2/A3 is switchable in BM only.

Fast A2/A3 switch is definitely needed on main window, same (or close to) as it is in ESDR2. It is certainly crucial for those who use combination of RX/TX antennas (or two antennas< for example directional and multi-directional) on A2/A3 simultaneously.
For those who not need it - just make feature visibility "On/Off" in Options menu or in BM.

**Comment by John-KC2QMA** [comment]
Yes basic antenna selection in main window is desirable and/or have the option to show or hide.

**Comment by rvolchkov** [comment]
Implemented
