### ISSUE TITLE
Add the possibility to use transvertr for 28Mhz on tranverter buttons 

### ISSUE THREAD

**Issue by SM4IVE** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#32]
Its not possible to use 116Mhz as Lo and use Band 1 as 2 m   it seems hard coded to 432 Mhz
Due the fact i dont want to use the 2M standard for tranverter use.
Make it possible to use any band any lo freq in the transverter modul

**Comment by rvolchkov** [comment]
Implemented
