### ISSUE TITLE
Autostart option

### ISSUE THREAD

**Issue by DK8JV** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#35]
I have the ExpertSDR3.exe in my Windows autostart, and it presents me the EESDR3 main window from where I can open, and then switch on my transceiver.

I think it could be needful if one could have automatically switched on the transceiver at the computer startup. 
I often run my station remotely - currrently via RemoteHams, hoping for the EESDR remote solution - but when my PC reboots (it does it quite frequently) I'm locked out of my station.

Could such an option be added to EESDR3, maybe by means of some command line parameters to ExpertSDR3.exe?

Best regards, 
Eberhard, DK8JV

**Comment by rvolchkov** [comment]
Implemented
