### ISSUE TITLE
Network request for RadioSync.

### ISSUE THREAD

**Issue by ct1drb** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#44]
Hello there,

would be possible to give a network client option to RadioSync???

Instead to define only an USB port to use with third-party software, why not to have option to choose a network port for third-party software??

Maybe you can add Kenwood TS-2000 or others.

Reason would be to use with other third-party software and at same time to avoid usage of USB to RS232 adapters.

Best 73.

CT1DRB/OK8RB
David Quental

**Comment by rvolchkov** [comment]
Now RadioSync works as it should
