### ISSUE TITLE
Bug RX1 +RX2  bad audio with sample rate 312Khz

### ISSUE THREAD

**Issue by F4DNK** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#45]
Expert SDR3 0.11.0. alpha
MB1 prime I7700 Windows 10
when both RX1 and RX2 receivers are active the audio is very bad with the sample rate scop at 312khz
with the sample rate at 156 KHz the audio is very good on both receivers. I find the same problem on sdr2 1.3.9

73

**Comment by ExpertSDR3** [comment]
a separate bug tracker has been created for errors  https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER
