### ISSUE TITLE
Bug E-coders  tx/play

### ISSUE THREAD

**Issue by F4DNK** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#46]
SD3 0.11.0 Alpha
MB1 Prime I7700 + Windows 10
there is a problem with the Tx /play function not working on my E-coder. I can't find the on/off functions for SQL and PA Sincerely

73 F4NK

**Comment by ExpertSDR3** [comment]
a separate bug tracker has been created for errors  https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER
