### ISSUE TITLE
TCP server option in RadioSync

### ISSUE THREAD

**Issue by ok1dsz** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#48]
Hi
thanks for introducing the RadioSync tool. Could it be possible to extend it the way, that besides the COM ports also an option to act as a TCP server would be available? It would allow direct connection with some loggers having possibility of CAT over Ethernet, such as recent releases of DXLog.
thanks
Zdenek OK1DSZ
PS. It is perhaps duplicating issue #44, but David is asking for a client option there

**Comment by rvolchkov** [comment]
Now RadioSync works as it should
