### ISSUE TITLE
Please add "RX Antenna" button again

### ISSUE THREAD

**Issue by Dieter9** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#50]
ESDR3 already makes a good impression but I really miss the button "RX-Antenna" from ESDR2.

Beside my normal, rotatable transmitting antenna I have an active, broadband receiving antenna,
which I often use to estimate the propagation conditions. The "band manger" in ESDR3 is very nice, 
but totally unsuitable for the purpose.

In ESDR2, it was a nice thing to be able to switch quickly between the two antennas.

73 de Dieter, DK6OV

**Comment by OK8WW** [comment]
I totally agree. I also use this function in conjunction with E-Coder to connect RX antennas for low bands.

73 Richard OK8WW
