### ISSUE TITLE
Make the horizontal zoom level of ESDR3 the same as ESDR2

### ISSUE THREAD

**Issue by williamscody** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#51]
Environment:
Intel Core i7-7700K CPU at 4.2GHz
AMD Radeon 580 Graphics Card
32GB RAM
Windows 10 Pro, version 21H1, 64-bit (AND Windows 11 Pro, 64-bit)
SunSDR2DX, S/N EED06202100503, Firmware 72.8
ESDR3 0.10.0

Issue/Suggesion:
I noted that maximum zoom in ESDR2 is far greater than ESDR3.  Pictures are attached.  Both versions were using the same sample rate, centered on the same frequency.

It is often useful to zoom way in to learn more about a signal.

![ESDR2 Full Zoom](https://user-images.githubusercontent.com/16505794/152280319-ce5af4ce-5a1c-4606-9ebe-f1f5b3d6e2bf.png)

![ESDR3 Full Zoom](https://user-images.githubusercontent.com/16505794/152280329-a20dcb80-dca8-4bc1-8650-d0eab4e77dee.png)

**Comment by rvolchkov** [comment]
Now it works the same
