### ISSUE TITLE
Minor: Consistency and Clarity on Global Mute indicator

### ISSUE THREAD

**Issue by reflectingme** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#55]
Software: ExpertSDR3 0.11.0 alpha BUILD: 30122021
Computer: iMac OSX Monterey 12.2
Radio: SunSDR2DX

Just a thought, as mentioned as a suggestion in a issue report #251, a minor cosmetic item but may be worth considering nonetheless.

The **Global Mute** indicator is somewhat confusing.  A suggestion for clarity going forward would be to use a green icon for when sound is on, 
![EESDR3-Volume_Normal](https://user-images.githubusercontent.com/47534300/153031006-d0303855-aa3f-4f5c-987e-fa994c588e52.jpg)

... and a red icon with a cross for when Global Mute is selected i.e. sound is muted
![EESDR3-Volume_global_muted](https://user-images.githubusercontent.com/47534300/153031087-722582fd-5442-4912-8589-f0346a67dad3.jpg)

Maybe even a small further refinement of making the icon grey (as it is currently) when the volume slider is all the way down at 0%.
![EESDR3-Volume_zero](https://user-images.githubusercontent.com/47534300/153032155-68a9215a-699f-4228-9801-09635d7d5281.jpg)

This would allow users to differentiate between volume off/set at zero, volume in use, and Global Mute enabled.

**Comment by deR0BI** [comment]
Можно ещё добавить опцию "приглушить"  звук. Для удобства в so2r

**Comment by rvolchkov** [comment]
It works differently now
