### ISSUE TITLE
TCI Audio sampling options / улучшения для TCI Audio (for 0.13a) 

### ISSUE THREAD

**Issue by VK6NX** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#56]
Пожелания по улучшениям TCI аудио для 0.13a:
1. Очень хотелось бы видеть не только более гранулированый sample rate но и его синхронизацию в frame size. Для ESDR basic, наверное будет достаточно сделать UI пресеты (вида "СW, DIGI, SSB, eSSB") и установить там некие "средние" соотношения Sampling Rate / Frame Size. Для ESDR enhanced хотелось бы иметь возможность возможность выбора обеих параметров юзером.
2. Относительно Bit Rate -  возможность установки в зависимости от выбранного пресета (см. пункт 1), а для enhanced - возможность выбора юзером.
3. Пожалуйста не останавливайтесь на Sampling Rate 16/24/32, сделайте еще и 8kHz. поскольку соотношение 8kHz/8bit/10ms Frame Size - возможно (надо экспериментировать!) даст наилучшие результаты для уменьшения delay и latency для CW (и возможно для DIGI).
4. Очень было бы здорово, если бы еще default packet interval тоже можно было бы имплементировать хотя бы на уровне пресетов.

Спасибо.

------------------------------------------------------------
Reference for EN-speaking 
The above request for upcoming (0.13a) TCI Audio enhancements. It is all about making TCI Audio stream Sampling Rate / Frame Size / Bit Rate / Default Packet Interval more granular and selectable via UI and TCI commands.

**Comment by rvolchkov** [comment]
Внедрено в версии 1,9
