### ISSUE TITLE
Add microphone equalizer full reset and individual band reset

### ISSUE THREAD

**Issue by williamscody** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#57]
Environment:
Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz, 32GB RAM
Windows 11 Pro, 64-bit, version 21H2
AMD Radeon 580 Graphics Card
SunSDR2DX, S/N EED06202100503, PCB Revision 1.1, Firmware 76.8
ESDR3 0.12.0 alpha, Build 18022022

Background:
As I was adjusting the EQ for my mic, I realized there was no way to completely reset all EQ settings, nor was there a way to rest a specific band (including frequency and Q).  The only thing a right-click does is bring a specific frequency dot back to its original gain, which is fine by itself, but more is needed as below:

Request:
1) Add a "reset all" button to the EQ window
2) Add when clicking a specific band icon, ALL of its parameters are reset (frequency, gain and Q) - see attached pic.
![2022-02-18 13_42_23-ExpertSDR3 SunSDR2DX EED06202100503](https://user-images.githubusercontent.com/16505794/154760282-4dfae037-9af0-4e8d-b2dc-0b4e0d6aff78.png)

**Comment by ExpertSDR3** [comment]
Added in version 1.0.3
