### ISSUE TITLE
[ExperSDR3 / Linux] Скрипт установки Esdr3/ Installstion script for Esdr3

### ISSUE THREAD

**Issue by bastonc** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#58]
Для всех пользователей Linux
Написал и протестировал скрипт инсталляции программы ExpertSDR3
Что подразумевает инсталляция - создание ярлыка в системном меню, разрешение доступа к портам USB для работы Екодера под пользователем (без рута).
В случае использования Colibri выгрузка соответствующего модуля ядра для корректной работы приемника.
Как работает инсталлятор.
Скачайте архив [по ссылке на Гугл диске](https://drive.google.com/file/d/1iQFtW-3BX0-D-5hDKW4RvHyQR7cKM7Z-/view?usp=sharing)
Распакуйте архив в папку с программой expertSDR3 (рядом с expertsdr3.sh)
Убедитесь, что все файлы .sh разрешены для исполнения
Запустите в терминале файле install.sh
Он создаёт desktop файл в /usr/share/application 
Копирует файл EcoderUSB в /opt/EcoderUSB/ этот файл нужен для службы systemd
Создаёт службу systemd, которая после запуска системы автоматически выполняет скрипт с командами для активации Ecoder для пользователя.

Скрипт uninstall.sh останавливает, и удаляет службу systemd, а так же удаляет desktop файл из /usr/share/application (и соотвтетственно ярлык из меню системы)
Скрипт проверен в Ubuntu и Fedora

Небольшой скрипт, но достаочно удобный, я его использую какое-то время и вывод ярлыка в меню занимает при получении новой версии всего несколько секунд.
Если компания Эксперт электроника сочтет скрипт полезным - может включить его в официальный архив с программой, что бы пользователь получал все в одном архиве вместе с программой. Или возможно напишет что-то своё подобное )

For all users Linux system.
I am testing installation script. How it's work.
Download archive (link https://drive.google.com/file/d/1iQFtW-3BX0-D-5hDKW4RvHyQR7cKM7Z-/view?usp=sharing)
Unzip archive in Expertsdr3 directory (near with expertsdr3.sh)
Check exutable bit, if needed - resolve for run all .sh files (chmod +X <filename.sh>). 
Run install.sh
1. Installer create desktop-file in /usr/share/application - it's created icon in system menu (see screenshot) 
2. Copy file EcoderUSB.sh into /opt/EcoderUSB this file run after boot system (from systemd)
it file resolve access to Ecoder for user (without root)
3. Create systemd service (service has name EcoderUSB) for enable Ecoder after boot.

Unistall.sh - disable service EcoderUSB in systemd, 
remove  /opt/EcoderUSB/EcoderUSB.sh, 
remove desktop file from /usr/share/application.

Tested in Ubuntu, Fedora. 
If intresting, and installer will not have problem in our systems - we can asked EE include this installer into pakage with ExpertSDR3 )))

![IMG_20220219_112852_694](https://user-images.githubusercontent.com/37752012/154795727-8631f727-2e3e-49d3-b6f0-09e0557ddea1.jpg)
![IMG_20220219_112846_228](https://user-images.githubusercontent.com/37752012/154795728-67fe98a9-f20a-4b46-9269-239f5229ad8d.jpg)

**Comment by rvolchkov** [comment]
Спасибо большое за предложение, внедрим

**Comment by bastonc** [comment]
Сделал более совкршенный скрипт, который позволяет устанавливать несколько версий (в текущей реализации возможна только одна). Ставит ту версию в папки которой запускается скрипт инсталляции, лежит тут - https://drive.google.com/file/d/1gnsF5lJe4KCaC8_Zg46Zfhq3Ndf5kHgF/view?usp=drivesdk

**Comment by rvolchkov** [comment]
Список изменений в новой версии программы для Linux:
1. Программа устанавливается в папку /opt/ExpertSDR3
2. При установке программы автоматически создаются ярлыки в меню "Все программы" для ExpertSDR3 и RadioSync
3. При установке программы автоматически создается правило для USB-утсройств. Таким образом приемник ColibriNANO и панели управления E-Coder2, E-Coder работают без дополнительных манипуляций с системой.
4. При удалении программы с помощью [Uninstal.sh](https://uninstal.sh/) все описанные выше действия отменяются.
