### ISSUE TITLE
E-Coder adjustments

### ISSUE THREAD

**Issue by ExpertSDR3** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#6]
When I use the E-Coder knobs to adjust, say the CW keyer speed or AGC levels, the value isn't displayed like is when I use the mouse-scroll wheel to adjust them. Having this is quite helpful and would be nice if the feature could be included.
![142750298-470b1139-8688-4076-8902-dd48ee278449](https://user-images.githubusercontent.com/93903520/142750977-a8b244c2-393a-4ab7-b421-0a0693288705.png)

**Comment by rvolchkov** [comment]
Implemented
