### ISSUE TITLE
Device manager window resize

### ISSUE THREAD

**Issue by F1DJY** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#60]
F1DJY
Sunsdr2Pro
W11 21H2, EESDR3 0.12.0A Build 1802

Device manager window
I observed that the window can be reduced a bit in width, but not in height and the dimensions are not remembered. With a 4K screen it would be desirable if it could be much smaller.

**Comment by rvolchkov** [comment]
Duplicates #26
