### ISSUE TITLE
Control over NR and/or ANC

### ISSUE THREAD

**Issue by Kb2uka** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#61]
EESDR v3 0.12.0 alpha
iMac Monterey
Sunsdr2dx 

Would love to have control over the NR to set parameters to my liking. Would also enjoy being able to customize settings in the ANC. 

Thanks for all that you are doing with the software. 

Doug
Kb2uka

**Comment by W1SPS** [comment]
And maybe adaptive (learning) noise control like SDR Console 3 has. Sometimes that's the only thing that handles the noise.

**Comment by rvolchkov** [comment]
You can change NR - Quality and switch between 3 types of ANC.
We do not plan to complicate ESDR3 settings.
