### ISSUE TITLE
GUI change to AGC "Auto gain" control

### ISSUE THREAD

**Issue by G4ENZ-Martin** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#62]
Without "Auto gain" selected, the AGC gain can be adjusted from the mouse wheel or by using the E-coder control.

With "Auto gain" selected, please could the Auto gain **threshold** be adjusted by using the mouse wheel or the E-coder? 

I like Auto gain, but I find that I am regularly changing the threshold level as I change modes or if a weak station comes onto the frequency.

**Comment by reflectingme** [comment]
> Without "Auto gain" selected, the AGC gain can be adjusted from the mouse wheel or by using the E-coder control.
> 
> With "Auto gain" selected, please could the Auto gain **threshold** be adjusted by using the mouse wheel or the E-coder?
> 
> I like Auto gain, but I find that I am regularly changing the threshold level as I change modes or if a weak station comes onto the frequency.

Isn't changing the threshold level in Auto Gain _pretty much_ the same as manually changing the gain though, Martin?

**Comment by G4ENZ-Martin** [comment]
Not really John. On SSB I like to leave the threshold at about 15dB. With auto gain, it sets and maintains this level as I change from band to band without any intervention from me. Similarly on CW, I set it at 6dB and auto gain maintains this across all conditions. On occasions, I might get called by a weak station and need to change the threshold down a few dB but I still want the autogain to track my ever changing noise level.

**Comment by reflectingme** [comment]
Yes, I get you now, Martin.  Might be good to have an Auto Gain threshold set per Mode, perhaps?

As the code for Auto Gain is pretty much there already, to include a check condition for current operating mode might not be too much more work.

**Comment by G4ENZ-Martin** [comment]
I think there is already a suggestion (#3) posted asking for Threshold to be stored by mode. I think that's a good idea too.

**Comment by rvolchkov** [comment]
Duplicates #3
