### ISSUE TITLE
SSB - USER defined filter - bandwidth setting

### ISSUE THREAD

**Issue by IZ0JNY** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#63]
hello,

would it be possible to insert a small menu / window to enter the passband of the user defined SSB filter? for now you have to drag and drop the line on the waterfall, but it would be useful to have a small window or a small menu where you can enter the frequency, perhaps with a cursor.

**Comment by reflectingme** [comment]
Is it accuracy you are after here?  If so, simply zoom as far in as you wish on the frequency and the physical width of the pass band filter gets larger on the screen, you can then select with greater accuracy.

**Comment by John-KC2QMA** [comment]
Yes I have wanted the ability to directly enter and save my own filter presets for a long time.

**Comment by John-KC2QMA** [comment]
Thank you for adding this to the latest alpha of eSDR3.

**Comment by rvolchkov** [comment]
Implemented
