### ISSUE TITLE
RX antenna selection

### ISSUE THREAD

**Issue by lc7x** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#66]
RX antenna selection
As of today, we go to band manager and select antenna port A2 or A3 on HF. If you select e.g. A3 for RX antenna and keep A2 for TX, there is not a rapid way of turning RX antenna ON or OFF. Could this be an option on the front panel like in V2 of EESDR software. You can quickly toggle between RX and TX antenna as you receive antenna.

**Comment by OK8WW** [comment]
My whole setup for low bands is based on that. Therefore I am using v2, because there is no way to toggle RX antenna from E-Coder.

**Comment by ExpertSDR3** [comment]
In version 0.13 there will be control of the antenna switch on the main window.

![image](https://user-images.githubusercontent.com/93903520/175298347-cdf13d76-5d19-46b6-8082-fea7486188d8.png)

**Comment by f6ctt** [comment]
i confirm that we  need a button and/or an e-coder button to switch quickly the receive between A2 and A3. 
it's absolutely necessary when we use a receive antenna like a Beverage
Thank you in advance.

**Comment by lc7x** [comment]
As mentioned in the EE tester chat on Telegram. Thanks for adding RX antenna selection. Another function that was used in V2 of EESDR software was the possibility lock one of the antenna ports for RX antenna only.  If we i.e., use A2 for TX and A3 for **RX only**. It would be good to lock one of the ports in the menu / setup. You can easily by mistake switch wrong antenna and you TX into you RX antenna system, everything from preamplifier and other components in you RX antenna system can get damaged.

**Comment by rvolchkov** [comment]
Antenna selection is implemented, RX only duplicates #100
