### ISSUE TITLE
audio track problem from the Play panel

### ISSUE THREAD

**Issue by Antonello66** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#67]
hello, eesdr 12.1 alpha (3.0) when I send an audio track from the front panel of the software on PLAY the track is intermittent and the transmission power drops, thanks.

**Comment by ExpertSDR3** [comment]
In version 0.13, TX playback will be in maximum volume.

**Comment by rvolchkov** [comment]
Implemented
