### ISSUE TITLE
Transverter options

### ISSUE THREAD

**Issue by OK1YA** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#70]
1. Band manager - it would be possible to add the ability to set more than 5 XVRT bands (UHF / SHF). 8 bands would be fine: o))
2. Band manager -  it would be possible to add the option to set antenna output A1 (RX / TX) for transverters.  Some SHF transverters need more power (1-2 W @ 144MHz)
3. in transverter manager  it is not possible to set a frequency higher than 20 GHz
4. would it be possible to extend the Bands panel with activated transverter bands?
Tnx
Mek, OK1YA

**Comment by OK8WW** [comment]
I absolutely agree, this is also necessary for SunSdr2 QRP, where it is not possible to use ADC IN and DAC OUT. SunSdr2 QRP is an excellent solution for microwaves.

73 Richard OK8WW

**Comment by eb3frn** [comment]
Hi
yes, can be great add more bands and put more than 20GHz, for example up to 300GHz.
I've the sunsdrpro2, is possible assign the ext ctrl pins for every xverter band? the idea is use to switch different xverters.

Thanks a lot.

73! Iban
eb3frn

**Comment by rvolchkov** [comment]
Duplicates #127
