### ISSUE TITLE
Suggestion- DEV release V3 13 08062022 Panel meters

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#72]
Please add ability to resize pop out panel meters

also, a nice touch would be having the Mic panel meter background color change when in TX mode, a soft blue or red perhaps even amber would look nice, then in RX mode the background return to normal.

**Comment by ExpertSDR3** [comment]
Background change for TX mode has already been added
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/93903520/173523707-7a31512e-044c-4cf5-88a6-a0bf5d979624.gif)

**Comment by N8SDR007** [comment]
Thanks

**Comment by rvolchkov** [comment]
Implemented
