### ISSUE TITLE
Dev release V3 13 08062022- peak hold view or slowed refresh of peak in viewing area of panadapter

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#75]
Like with Thetis, the ability to hold for a small fraction of time the peaks and markers of the signal captured in the viewing bandwidth of the pan adapter, with audio frequency markers available to the open Passband you have set in RX filter widths

making it easy to view problem audio frequencies, hotspots and areas which may need boosting or reduction in EQ gain

**Comment by Kb2uka** [comment]
Fantastic suggestion.

**Comment by ExpertSDR3** [comment]
You can attach an example in the form of a picture or a short video to understand how it works?

**Comment by N8SDR007** [comment]
Roman:

see this video link it explains what I am suggesting https://www.youtube.com/watch?v=mLVZuK1zDkQ

Not in the video you will see a marker showing the dBm peaks and if possible, an option of coloring the peaks like they have done as well..

Reach out to Ritchie if need be, He likes the SunSDR2DX he has as well as his Anan rigs

**Comment by 1972igor** [comment]
A very good offer !!It should have been done a long time ago!! Support

**Comment by f6ctt** [comment]
like with Thetis too, if we can switch Off totally the Waterfall, Panadapter ... brief everything that use the bandwith ,  it's an interest thing when we use the remote desktop (Windows 10)  or other remote system, with a poor line adsl  or other internet connection with very  low speed 
Thank you

**Comment by ExpertSDR3** [comment]
In Version 0.13, the peak hold spectrum display will appear

![ezgif-3-aae7a6b196](https://user-images.githubusercontent.com/93903520/183442069-14b9bd08-8a3b-475a-b957-e6fca68cc060.gif)

**Comment by N8SDR007** [comment]
Thanks

will there be ability to change your peak hold colors and peak hold time?

thanks for the update

**Comment by ExpertSDR3** [comment]
The peak spectrum supports customization.

![Снимок экрана от 2022-08-16 11-07-42](https://user-images.githubusercontent.com/93903520/184830062-8290ce7b-235c-4eab-8a53-0b1f98290ed7.png)

**Comment by rvolchkov** [comment]
Implemented
