### ISSUE TITLE
TCI audio level adjustment

### ISSUE THREAD

**Issue by kingsqueak** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#78]
With jtdx as an example, the output audio defaulting to 0db works fine, but the RX audio level is entirely too hot and it lends to less effective decoding.

I would like a mechanism in TCI where the audio levels can be adjusted from the EESDR3 software for applications that don't have a way to do this built in.

**Comment by rvolchkov** [comment]
Third-party software is responsible for signal level, JTDX developer is happy with TCI now.
