### ISSUE TITLE
The ALC/limiter should indicated how many db of reduction is taking place

### ISSUE THREAD

**Issue by kingsqueak** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#80]
The limiter in EESDR3 behaves better with every release.

I would like to see how hard the audio level is hitting the limiter. Currently you see that you are hitting close to 0 and the limiter is stopping the signal, but what you don't see is how many db of limiting is occurring. 

This is useful so that people realize they are pushing against the limiter as it colors the audio and causes background noise to raise. It would be very useful to know that we are hitting as an example 1db or maybe 10 db of "compression" effect based on the level of the audio hitting the limiter.

**Comment by rvolchkov** [comment]
What we've created now is a more friendly GUI.
We may think about expanding PROC menu later in far feature.
