### ISSUE TITLE
Feature Request - Add remote TCI Endpoint in EESDR RS

### ISSUE THREAD

**Issue by iw7dmh** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#87]
A local (intranet) TCI endpoint is needed in Eesdr-Remote-System. It will allow the TCI enabled devices to be aware of the rig status. There is no need that this kind of endpoint will accept incoming commands (this should be a EESDR client responsability) - on the contrary it should notify every status change to all the connected clients.

The following schematic should clarify the point.

Best regards
Enzo, iw7dmh

![Remote TCI Endpoint](https://user-images.githubusercontent.com/87143145/181769627-068c3f97-b53c-41eb-bfea-416b82f6dc0f.jpg)

**Comment by DK8JV** [comment]
Me too, I'm in need of such a solution for controlling my automatic antenna swich and the tuner for my dipole.
Both relate on the frequency information provided by TCI (through a CAT interface) Currently, the only way to run my station remotely is to use a VPN connection so my remote EESDR3 instance's TCI server provides that information.
Having a local TCI endpoint, as proposed by Enzo, would overcome this problem and make remote operation a lot easier.
Such an endpoint could possibly be added to the starter.exe program. This would be really great. (another place could be, perhaps, within the firmware of the SunSDR device itself, but I don't think this is a good solution. A piece of software running on whatever local computer in your LAN would fully suffice.

VY 73
Eberhard, DK8JV

**Comment by rvolchkov** [comment]
We will not implement that, since TCI was initially designed as local server. To make it go web, you may use VPN.
