### ISSUE TITLE
receiver equalizer, which affects the frequency response of the filter DSP  SETUP Taps

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#91]
обнаружил, так это неверное соединение в программе переключение прямоугольности фильтра и магнитофона. В эфир все идет согласно изменениям по Taps, а вот пишет только на самом низком значении 512.работа эквалайзера приёмника , который влияет на АЧХ фильтра эквалайзер должен работать в цепи УНЧ и только там, а не на выходе линейном или в точке откуда берется запись магнитофонов
I found out that this is an incorrect connection in the program switching the squareness of the filter and the tape recorder. Everything goes on the air according to the Taps changes, but writes only at the lowest value of 512. the operation of the receiver equalizer, which affects the frequency response of the filter, the equalizer should work in the UHF circuit and only there, and not at the linear output or at the point where the recording of tape recorders comes from

**Comment by rvolchkov** [comment]
Линейный аудио выход предназначен для записи соревнований, с минимальной нагрузкой на ЦП, поэтому в нем не используются фильтры высоких порядков.
Эквалайзер приемника не участвует в обработке сигнала линейного аудио выхода.
