### ISSUE TITLE
Slider between Spectrum and Waterfall & zoom into current tuning

### ISSUE THREAD

**Issue by W1SPS** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#92]
Hey all, If EESDR3 has this functionality already feel free to delete this. I'm new to the software and maybe I haven't found this yet.

1. A slider or drag bar between the Spectrum display and waterfall to slide the screen up or down the band without changing your tuning. Just so you can slide up and down the band to see what is around. Or just to simply center where you are tuned to the screen.  I always use the wrong button on the wrong half of the screen and drag myself off frequency. A dedicated slider would be easier (at least for me).

2. Maybe an adjustment wheel to zoom in on where you are tuned for better detail of the spectrum and waterfall in that location. Again it's not that intuitive right now and the button selections in the bottom left of the screen to limit the band you're watching is a pain.

3. A button that could center the frequency you are on to the center of the screen in a single click. Also handy in my opinion.

73
Rich
W1SPS

**Comment by reflectingme** [comment]
Hi Rich.. if I understand you correctly...

1. Right click and drag anywhere in the spectrum display or waterfall to slide up and down the band
2. Right click and drag in the bar between spectrum display and waterfall at the frequency you wish to zoom in or out from.
3. Several ways: (a) left click and drag the blue triangle in the bar to your frequency, (b) right click and drag within your selected frequency to move the range on your frequency

Not sure if I fully understood your questions, but try those and see if they do what you wan...

**Comment by W1SPS** [comment]
Well I was talking about a slider or roller to do that. I always click with the wrong button in the wrong space. When trying to center the waterfall to the frequency I'm on I almost always drag myself off frequency. I'd like a single click to center the frequency I'm on to the center of the screen.  Sometimes I like to see what it up or down the band from me and would like to drag my current frequency to the left or right but stay on frequency. It would also be nice if the waterfall didn't skew while doing that.

**Comment by rvolchkov** [comment]
For now, we'll keep things as they are, we are focused on expanding core functionality.
