### ISSUE TITLE
Wish: Please (re)enable Squelch for SSB

### ISSUE THREAD

**Issue by DK8JV** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#93]
Dear all,
I'm running EESDR 0.13.0. buld 08072022.
I am desperately missing the squelch functionality in SSB.
And I would be very happy if it could be reenabled in the final version of EESDR3. 

vy 73
Eberhard, DK8JV

**Comment by John-KC2QMA** [comment]
Yes please. Need "All Mode Squelch"

**Comment by s-car-go** [comment]
I agree completely. I use squelch all of the time when operating SSB.

The current implementation of squelch is triggered by signal level. This is the way is always has been done. I suggest that there is a better way to trigger the squelch by using spectral content rather then level triggering.

If anyone wants to see this in action just tune in to this WEB SDR   http://websdr.lumpkinschools.com/
and play around with strong and weak signals and rate its performance for yourself. Notice there are no controls for the squelch other than ON/OFF. It does a great job IMHO. I would like to see this type of squelch incorporated into SUN radio products.

I am currently working on implementing this into the Thetis software used for the Apache radio products.


Dave...  WB5QFZ

**Comment by rvolchkov** [comment]
Implemented in the latest 1.0.2.

**Comment by DK8JV** [comment]
Thank you so much!
