### ISSUE TITLE
CW autotune

### ISSUE THREAD

**Issue by rkayakr** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#96]
Please add a function to center tuning on a CW signal at a click.
Many transceivers have this useful function.
The SunSDR2 DX has many great features for SSB opertaion. For CW it starts out behind due to lack of QSK, side tone latency issues that require careful management and lack of autotune.
The autotune feature is a great help to CW operation that makes click to tune useful for CW.

BTW - this function should operate whether you are using a skimmer or not. Many of us don't primarily interact through a skimmer and begrudge launching yet another resource and screen real estate hogging application. Particularly to do a relatively simple functions other radios do without the complication.

https://eesdr.com/en/forum-en/suggestions/9896-cw-autotune#22527

    Bob
      KD8CGH

**Comment by rvolchkov** [comment]
Thanks, but we do not plan to implement this feature any time soon.
