### ISSUE TITLE
RadioSync TCI Command via CAT

### ISSUE THREAD

**Issue by tjasperme** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#98]
With SDC there is the possibility to transmit TCI commands within a CAT command. The command is just prefixed with "TC". MixW example: <CATCMD:TC:agc_mode:0,normal;> or <CATCMD:TC:rx_filter_band:0,1400,1600;> 
Can you also implement the function in RadioSync?

**Comment by ExpertSDR3** [comment]
If I add a direct command forwarding without additional prefixes?

**Comment by tjasperme** [comment]
should be ok, if I can send it via cat.
thanks in advance.

**Comment by ExpertSDR3** [comment]
The RadioSync utility has added an IQ signal output to a sound card with sampling frequencies of 48/96/192/384 kHz.
Added duplex forwarding of TCI commands via COM port.

![image](https://user-images.githubusercontent.com/93903520/192990799-9b765521-074c-412c-b093-6b57f753fc7b.png)

**Comment by tjasperme** [comment]
Thanks for Implementation, now you have a seperate port for TCI transfer - the idea was to send an TCI command via CAT(TS480) from the digi mode program.

best regards

**Comment by ExpertSDR3** [comment]
Do you mean sending commands only to ESDR3 ?
If so, then I can add a search for the prefix TCI in the CAT command to the parser: TCIAF:55;.

**Comment by tjasperme** [comment]
Yes, only to ESDR3. If it's no problem for you please use the prefix "TC:"
so I don't need to change my macros 😀
best regards and mny tnx in advance


Am Do., 29. Sept. 2022 um 15:52 Uhr schrieb EE ***@***.***>:

**Comment by ExpertSDR3** [comment]
I will add this functionality.

**Comment by tjasperme** [comment]
Tanks!

Am Do., 29. Sept. 2022 um 16:36 Uhr schrieb EE ***@***.***>:

**Comment by ExpertSDR3** [comment]
Implemented in RadioSync 1.1.0 .

**Comment by tjasperme** [comment]
Thanks for Implementation, now you have a seperate port for TCI transfer -
the idea was to send an TCI command via CAT(TS480) from the digi mode
program.

best regards



Am Do., 29. Sept. 2022 um 11:10 Uhr schrieb EE ***@***.***>:
